// Game types
export type {
  Attribute,
  DamageType,
  Condition,
  Distance,
  DifficultyLevel,
  RollResultType,
  RollResult,
  DamageSeverity,
  RuleSystemId,
  WeaponHandedness,
  WeaponData,
  ArmorData,
  DomainType,
  ClassData,
} from './rules';

export {
  ATTRIBUTE_LABELS,
  CONDITION_LABELS,
  DISTANCE_LABELS,
  DIFFICULTY_LEVELS,
  ROLL_RESULT_LABELS,
  DAMAGE_SEVERITY_LABELS,
  DOMAIN_LABELS,
} from './rules';

// Character types
export type {
  PlayerRole,
  Ancestry,
  Community,
  Experience,
  DomainCard,
  Scar,
  InventoryItem,
  CorruptionLevel,
  Character,
  CharacterRelationship,
  EnemyStatBlock,
  EnemyFeature,
  Faction,
  NPC,
} from './character';

export {
  getTier,
  calculateThresholds,
  getDamageSeverity,
  getHpChangeFromSeverity,
} from './character';

// Event types
export type {
  GameEvent,
  EventSource,
  GameEventType,
  PlayerActionEvent,
  PlayerRollEvent,
  CombatAttackEvent,
  CombatDamageEvent,
  GmSceneChangeEvent,
  FactionRelationChangeEvent,
  CorruptionChangeEvent,
  AgentOutputEvent,
  AgentType,
  SessionState,
  PlayerState,
  SceneState,
  RoundTracker,
  CombatState,
  CombatEnemy,
  ActiveCondition,
  TimelineEntry,
  RiskLevel,
  Suggestion,
  SuggestionOption,
  SocketMessageType,
  SocketMessage,
  GameIntentType,
  ParsedIntent,
  InputTextPayload,
  InputVoicePayload,
  InputVisionPayload,
  InputTextEvent,
  InputVoiceEvent,
  InputVisionEvent,
  InputParsedEvent,
} from './events';

// Agent types
export type {
  AgentMessage,
  AgentContext,
  AgentResponse,
  AgentGeneratedEvent,
  WorldLore,
  LocationData,
  CampaignTimelineEntry,
  RuleSystemData,
  RandomTable,
  RandomTableEntry,
  ConditionData,
  ImageGenerationRequest,
  ImageStyle,
  GeneratedImage,
  NovelRequest,
  NovelStyle,
  NovelChapter,
  Novel,
} from './agent';
